// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WpfCoreApp.EF;

#nullable disable

namespace WpfCoreApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250723061435_InitialDb")]
    partial class InitialDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WpfCoreApp.Mvvm.Model.Preference", b =>
                {
                    b.Property<bool>("ShowInSystemTray")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowInTaskBar")
                        .HasColumnType("bit");

                    b.ToTable("Preferences");
                });
#pragma warning restore 612, 618
        }
    }
}
