// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WpfCoreApp.EF;

#nullable disable

namespace WpfCoreApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260419112841_Employees-DGDVM")]
    partial class EmployeesDGDVM
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WpfCoreApp.Mvvm.Model.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("WpfCoreApp.Mvvm.Model.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 34,
                            Department = "HR",
                            IsActive = true,
                            Name = "Alice"
                        },
                        new
                        {
                            Id = 2,
                            Age = 40,
                            Department = "IT",
                            IsActive = true,
                            Name = "Bob"
                        },
                        new
                        {
                            Id = 3,
                            Age = 60,
                            Department = "Finance",
                            IsActive = true,
                            Name = "Charlie"
                        });
                });

            modelBuilder.Entity("WpfCoreApp.Mvvm.Model.Preference", b =>
                {
                    b.Property<bool>("ShowInSystemTray")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowInTaskBar")
                        .HasColumnType("bit");

                    b.ToTable("Preferences");
                });
#pragma warning restore 612, 618
        }
    }
}
